### ISSUE TITLE
BUG: Case messages are getting removed from the UI

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8879] opened 2024-11-06 17:58 UTC
**Describe the Bug**
We received a helpdesk ticket indicating that a Judge was certain that they sent a message to a docket clerk with a stamp Order attached, but this message was not displaying in DAWSON.  After reviewing the logs, we found that the judge did send the message to the docket clerk successfully. The message reply and the text of the message was available without error in the logs. We continued to review the logs and found that the Judge accessed the same message thread and received an error message shortly after sending it successfully.

Some assumptions/thoughts:
The user had multiple tabs open, might have had the original case open on multiple tabs and this confused the system?
The original message may have been overwritten in state 

We have not yet been able to recreate this issue when testing.

Messages that go missing can cause quite a bit of confusion, and as we have seen, multiple documents are not getting served in a timely manner if the messages are no longer available in the case or in the user's message inbox.  This may also cause incorrect "blame" on various Court sections if a user doesn't get a reply (when in fact they did).

**Business Impact/Reason for Severity**
Medium

**In which environment did you see this bug?**
Production

**Who were you logged in as?**
Multiple Court users

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Court Users reported to us that their messages that they sent no longer appeared in DAWSON

**To Reproduce**
Uknown at this time

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**

Here is a screen grab of the events leading up to when the error message was thrown
![Image](https://github.com/user-attachments/assets/736af381-209e-47b2-909e-89cd17fc3d7b)

Here is a screen grab of the message that caused the error:
![Image](https://github.com/user-attachments/assets/6cfa2e61-d3ba-4199-a270-848322d044b8)

Here is a screen grab of the Production logs going back 6 months. Looks like this error has been thrown 108 times. Not sure at this point the exact scenarios for these:
![Image](https://github.com/user-attachments/assets/e33e05ca-d3f9-45b2-bfe6-4cd560195221)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by En-8** [comment] 2024-11-19 14:48
I think I've figured out a way to reproduce this issue (or at least something very similar) in the specific case where a Judge is forwarding a message after having stamped a motion. To reproduce:

1. As docket, file and serve a motion
2. Send a message to the associated judge, attaching that motion.
3. Log in as that judge.
4. Click on a DIFFERENT message.
5. Use docket number search to navigate to case details for the case on which you filed a motion
6. Click the 'document view' tab
7. Click the motion
8. Click the stamp button
9. Accept or deny the motion, submit.
10. At this point, the stamp process kicks off. You should ultimately land on a page
   that appears as if its a message on the case the motion was associated with
   but the motion that was stamped shows as "Document unavailable" while the stamp grant
   document appears as one would expect.
   At this point, you can inspect the requests in the network tab or look at the URL and
   see that the parentMessageId is the same ID as the message you viewed prior to navigating
   to the the relevant case details page (this is the bug).


This next bit I don't fully understand -- why the user gets to a point where they think
they've sent the message _successfully_. If I proceed to forward the message, I get a 400 error (the error we're seeing in the logs) that redirects me to the error page.

"Go back and try again" takes me back to the stamp page, where stamping a second time has the exact same problem. If I navigate away, that message still shows as a message in my inbox.

**Comment by En-8** [comment] 2024-11-19 22:12
> This next bit I don't fully understand -- why the user gets to a point where they think
they've sent the message successfully. If I proceed to forward the message, I get a 400 error (the error we're seeing in the logs) that redirects me to the error page.

Okay, I think I've figured out the disappearing messages now. This is actually a bug of two parts -- the first part is the flow I've described in my previous comment where stamping from the document view as a judge associates the stamp order document with whatever message thread you were _previously_ looking at.

The second part: Now, that message has a "poison pill" attached to it. When you then attempt to _reply to_ this message (the one that's not even supposed to be associated with the above stamp order and is likely even associated with a completely different case), the message is marked as "replied to" even though the user encounters an error (the one we're seeing in the logs). This message then falls off case messages and other views because we're using "replied to" to determine whether or not a message should show since we intend to show only the latest message in a thread (I assume, based on what I'm seeing).

**Comment by En-8** [comment] 2024-11-20 16:33
@cholly75 @ttlenard , I have confirmed that the Status Report Order and Stip. Decision flows are not impacted by the same issue that we have in the Stamping workflow.

**Comment by En-8** [comment] 2024-12-03 22:14
After discussing with @cholly75 , we've opted to deploy this fix ASAP without waiting for the data cleanup script, knowing that in the interim (b/w fix and data cleanup) we may end up with an increase of users reporting issues with messages.

In the event that a user is reporting errors trying to reply to or forward a message, here's the manual process for fixing the corrupt message:
1. Identify the message
    b. Either get the message ID from the user, or look up the "Message Entity was Invalid" error in the logs and grab the message ID from the `request.url` field. 
3. Identify the problem attachment(s) on the message
    a. Look up the message by its ID in the SQL database
    ```
    select * from dw_message as message where message.message_id = 'insertMessageIdHere';
    ```
    b. Note the `attachments` and `docket_number` fields
    c. In DynamoDB, query for each document from the attachments to check whether or not it's associated with the case: `pk = case|docketNumber` and `sk = docket-entry|documentId`. If your query returns a document, that one's good. If your query returns nothing, then that document is one of the problem documents. It is possible for there to be multiple problem documents, so check all of them.
    d. Alternatively, log into the UI, navigate to the message details of the message in question, and cross-check the visible attachment document IDs with those on the record in postgres -- the document IDs NOT present should correspond to the "Document unavailable" attachments.
   e. to be safe, you can also verify that the document does indeed belong to a different case.
4. Remove the problem attachments
    a. Update the `attachments` field to no longer include the problem documents. Modify the attachments json to remove the entire object the the documentId of the problem document, then update attachments as below:
```
update dw_message set attachments='[{"documentId": "thisWillBeADocumentId"}]' where message_id = 'thisIsTheMessageId';
```

**Closed as completed** 2024-12-08 05:06 UTC
Labels: bug, Medium Severity
