### ISSUE TITLE
Remove race condition when scraping PDFs.

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#581] opened 2020-11-27 06:56 UTC
@mark-meyer found a race condition in the process for scraping PDFs. The script that attempts to do that tries to load and save an entire case. Meanwhile other operations are running concurrently working with the same case, and they overwrite the previously saved information for the case in Dynamo, and the saved record gets lost. This process could also explain why we saw a high volume of writes in Dynamo when performing this operation. 

Upon further examination, these writes may be entirely unnecessary. All they are doing is saving a system generated UUID after creating a file with that UUID in the same bucket where the pdfs are stored. We already have a UUID, and we could re-use that for the scraped contents if we simply stored it in another location. It would be more efficient and less confusing as the UUID for the docketEntryId would match up exactly for the PDF and the file containing the scraped contents. 

One final thing is to remove files if there is a failure because previous attempts that encountered the DDB throttling probably created a bunch of files as they scraped and saved the contents, but did not clean them up upon DDB failure.

Tasks
- [x] Make sure we have long lasting retention on the SQS queue
- [ ] Restage the queue in the migration environment
- [ ] Create bucket for Document Contents in Terraform (or use a .txt extension in the same bucket)
- [ ] Allow the save to storage allow for mimetime specification (right now it forces PDF)
- [ ] Copy (or refactor) Lambda that saves the Document to the Documents bucket, to save the Document Contents to its new location
- [ ] Rather than write the case back to DynamoDB, attempt to index the document on behalf of the case in ES.
- [ ] refactor application to remove `documentContentsID` and look at the right spot for ☝️

**Comment by mmarcotte** [comment] 2020-11-27 06:57
Need to run on Migration Environment and Prod

**Comment by mark-meyer** [comment] 2020-11-30 19:56
From the code perspective it looks like we would be getting rid of `documentContentsId`. Any place that currently uses `documentContentsId` would instead use `docketEntryId` and simply reference a different S3 bucket. 

The question is, can we entirely avoid writing to DDB when we scrape the PDFs?  Are there places in the code where ef-cms needs to know *if* the document contents currently exist without looking in S3? For example, there is a code in `/shared/src/business/useCases/processStreamRecordsInteractor.js` that tests for this:

```
if (fullDocketEntry.documentContentsId) {
        // TODO: for performance, we should not re-index doc contents if we do not have to (use a contents hash?)
        try {
            ...
```

If we need to know if the docketEntry has content, we will still need to add some flag to the docketEntry row, which will cause the same issue of writing to the docketEntry concurrently (and creating all the stream events). Perhaps it is worth assuming the document contents exist in S3 and failing gracefully in the cases where it is not.

**Comment by adunkman** [comment] 2020-12-09 15:05
Mike read me into this issue last night. 

My current understanding of the landscape:

- PDFs need to be converted to text and indexed in order to provide full text searching of documents. 
- When a docketEntry’s PDF needs to be converted to text, the operation is queued for the `parseLegacyDocumentsInteractor`. 
- This process converts the PDF into text and stores the text as an intermediary output.
  - The text should exist outside of the index, because there are many operations which cause a re-index of cases but very few operations which change the expensive process of converting a PDF into its text.
- The docketEntry is then re-indexed, pulling the text contents from the intermediary output.

| Step | Current approach | Minimal change path forward |
|------|-------------------|-------------------------------|
| Store intermediary output | Text is converted to JSON and stored in S3. <br><br>The file is incorrectly marked as mime type `application/json` and is named a UUIDv4 with no extension, which causes issues when trying to identify which files are PDFs and which are JSON files containing PDF text. <br><br>The generated UUIDv4 needs to be associated with the docketEntry, which requires updating the associated case. Because this process may become queued or operate non-serially, there is a race condition which may cause updates to one docketEntry to be lost as another docketEntry is saved over the top of it. | Text is saved as text with a mime type of `text/plain` in S3.<br><br>By using the same UUIDv4 as the associated PDF but with a `.txt` extension, we can easily keep track of which files are related in S3.<br><br>The case does not need to be updated to store the association between a docketEntry and its text contents, because it can be derived, eliminating the race condition.
| Reindex case | Saving the case with the updated docketEntry causes a message to be queued to reindex the case via `processStreamRecordsInteractor`. | Save the case without performing any edits to queue the case for reindexing.[1] |

[1]: This is not an ideal path forward. Ideally, we’d be able to signal a reindex of the case in a different way. No-op saving the case will not solve the dynamodb throttling we experienced when processing legacy documents, however, it does prevent the lost data caused by the race condition. This would likely be filed as a backlogged ticket.

**Comment by adunkman** [comment] 2020-12-09 16:59
Had a productive pairing w/ Rachael and Cody. We refined the minimal changeset needed to remove the race condition: 

- We can switch `updateCase` to `updateDocketEntry` in `parseLegacyDocumentsInteractor`. Not sure why I didn’t think of this before, but I’m really happy to have fresh eyes on it! 
  - This eliminates the race condition while maintaining the usage of `processStreamRecordsInteractor`.

I also learned, through the chat (may be useful for future conversations):

- In some cases (orders, others I didn’t write down) where PDFs are generated by the system, the `documentContents` are stored directly by the system rather than scraped from the PDF. 
- `updateCase` should be performing a diff and only updating the changed fields, so it _should_ be equivalent to the changeset proposed here, and _should_ never have a problem with race conditions in this interactor. There may be a bug in that implementation.

**Comment by adunkman** [comment] 2020-12-10 16:05
I’ve been spending some time thinking about how to best avoid orphaned records in S3 when DynamoDB is throttled. I believe I’ve come to the conclusion that it is not possible without more significant changes. 

Background: 

- Orphaned records happen when `parseLegacyDocumentsInteractor` reaches its timeout after converting the PDF to text and saving the document contents but without saving the `documentContentsId` to DynamoDB. Contributing factors to this condition: 
  - Converting PDFs to text takes time. This means DynamoDB does not start its save operation until later in the timeout window.
  - This interactor is called in a batch with many other operations, which compete for DynamoDB resources.
  - Completing this interactor results in a series of events firing, resulting in more processes which compete for DynamoDB resources. 
  - Under throttling, DynamoDB takes longer to process save operations. 
- It is not possible to create a "transaction" or a way of rolling-back changes if the save does not occur, due to using distributed systems (S3 and DynamoDB).
- It is not possible to cleanly abort a DynamoDB save operation. We cannot be sure that the save operation has not been completed after the process has begun attempting the save. 
  - We could potentially overwrite the save operation to reset its state to a known point. This, however, suffers from the same throttling issue — we cannot be sure that it has completed successfully or cancel it if it times out.

Changes that could prevent orphaned files:

- Do not perform save operations. This would mean that the application would not know if a PDF has text contents associated with it. There are performance concerns from the team about this change. 
- Use predictable filenames. When `parseLegacyDocumentsInteractor` runs, it could check for previously failed operations and clean up their artifacts — however, we cannot know the previously randomly-generated UUID. If we knew what the filename was/should be, we’d be able to clean up or overwrite the artifacts.

**Comment by adunkman** [comment] 2020-12-11 15:47
Added https://github.com/ustaxcourt/ef-cms/issues/643 to track any work past this ticket. I believe #642 closes this issue, once verified fixed.

**Closed as completed** 2020-12-16 05:48 UTC
Labels: bug, high-severity
